/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The details about this particular message that have been sent to the callback  IMPORTANT: Depending on the flow, you may only see  one of the acknowledged or undeliverable keys with timestamps as their value
*/
export class CallbackInstanceResponseMessage {
    /**
    * The channel that this message was sent on. Either SMS, email or voice
    */
    'channel'?: CallbackInstanceResponseMessage.ChannelEnum;
    /**
    * The date/time that this message was acknowledged
    */
    'acknowledged'?: string;
    /**
    * The date/time that this message was marked as undeliverable
    */
    'undeliverable'?: string;
    /**
    * The content of the message
    */
    'content'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "CallbackInstanceResponseMessage.ChannelEnum"
        },
        {
            "name": "acknowledged",
            "baseName": "acknowledged",
            "type": "string"
        },
        {
            "name": "undeliverable",
            "baseName": "undeliverable",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CallbackInstanceResponseMessage.attributeTypeMap;
    }
}

export namespace CallbackInstanceResponseMessage {
    export enum ChannelEnum {
        Sms = <any> 'sms',
        Email = <any> 'email',
        Voice = <any> 'voice',
        NA = <any> 'N/A'
    }
}
