/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The object to specify which events callbacks should be enabled for.
*/
export class CallbackCallbacks {
    /**
    * A boolean flag specifying whether message reply callbacks are enabled.
    */
    'reply': CallbackCallbacks.ReplyEnum = CallbackCallbacks.ReplyEnum.Disabled;
    /**
    * A boolean flag specifying whether undeliverable message callbacks are enabled.
    */
    'undeliverable': CallbackCallbacks.UndeliverableEnum = CallbackCallbacks.UndeliverableEnum.Disabled;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "reply",
            "baseName": "reply",
            "type": "CallbackCallbacks.ReplyEnum"
        },
        {
            "name": "undeliverable",
            "baseName": "undeliverable",
            "type": "CallbackCallbacks.UndeliverableEnum"
        }    ];

    static getAttributeTypeMap() {
        return CallbackCallbacks.attributeTypeMap;
    }
}

export namespace CallbackCallbacks {
    export enum ReplyEnum {
        Enabled = <any> 'enabled',
        Disabled = <any> 'disabled'
    }
    export enum UndeliverableEnum {
        Enabled = <any> 'enabled',
        Disabled = <any> 'disabled'
    }
}
