/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomListCustomlabellistsInner } from './customListCustomlabellistsInner';
import { LinkInner } from './linkInner';

/**
* A custom list is a predefined list of options that can be inserted into a message or template. A list might be made up of capital city names, days of the week, incident types, business phone numbers and so on. Custom lists make it easy to add information quickly and consistently to your message content.
*/
export class CustomList {
    /**
    * Specifies the unique ID of the list
    */
    'id': string;
    /**
    * Specifies the name of the list
    */
    'name': string;
    /**
    * Specifies the type
    */
    'type': CustomList.TypeEnum;
    /**
    * Specifies the creation date of the list
    */
    'createdDate': string;
    /**
    * Specifies the sorting order
    */
    'sortType': CustomList.SortTypeEnum;
    /**
    * Specifies the linked status. When enabled the value selected for one channel is automatically applied on the other channels.
    */
    'linked': CustomList.LinkedEnum;
    /**
    * Contains the individual items that make up this list
    */
    'customlabellists'?: Array<CustomListCustomlabellistsInner>;
    /**
    * A [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) link object, describing all discoverable resources in relation to the original request.
    */
    'link': Array<LinkInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CustomList.TypeEnum"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "string"
        },
        {
            "name": "sortType",
            "baseName": "sortType",
            "type": "CustomList.SortTypeEnum"
        },
        {
            "name": "linked",
            "baseName": "linked",
            "type": "CustomList.LinkedEnum"
        },
        {
            "name": "customlabellists",
            "baseName": "customlabellists",
            "type": "Array<CustomListCustomlabellistsInner>"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "Array<LinkInner>"
        }    ];

    static getAttributeTypeMap() {
        return CustomList.attributeTypeMap;
    }
}

export namespace CustomList {
    export enum TypeEnum {
        Incident = <any> 'INCIDENT',
        Message = <any> 'MESSAGE',
        Contact = <any> 'CONTACT',
        Rss = <any> 'RSS'
    }
    export enum SortTypeEnum {
        AsDisplayed = <any> 'As Displayed',
        Ascending = <any> 'Ascending',
        Descending = <any> 'Descending'
    }
    export enum LinkedEnum {
        Disabled = <any> 'disabled',
        Enabled = <any> 'enabled'
    }
}
