/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Event } from './event';

/**
* List of events
*/
export class GetEvents200Response {
    /**
    * Provides the total number of records fetched. This attribute may return \"No records found\" when there are no events available.
    */
    'status'?: string;
    /**
    * List of events
    */
    'events'?: Array<Event>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<Event>"
        }    ];

    static getAttributeTypeMap() {
        return GetEvents200Response.attributeTypeMap;
    }
}

