/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Scenario } from './scenario';

/**
* List of retrieved scenarios
*/
export class GetScenarios200Response {
    /**
    * Scenario object
    */
    'scenarios'?: Array<Scenario>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "scenarios",
            "baseName": "scenarios",
            "type": "Array<Scenario>"
        }    ];

    static getAttributeTypeMap() {
        return GetScenarios200Response.attributeTypeMap;
    }
}

