/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListUsers } from './listUsers';

/**
* List users object
*/
export class GetUsers200Response {
    /**
    * List of retrieved users
    */
    'users'?: Array<ListUsers>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<ListUsers>"
        }    ];

    static getAttributeTypeMap() {
        return GetUsers200Response.attributeTypeMap;
    }
}

