/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FieldMapping } from './fieldMapping';

/**
* Import model object
*/
export class Import {
    /**
    * The resource identifier returned from the POST to /resources. Resource referred to must be a valid CSV, XML, or JSON file.
    */
    'resourceId': string;
    /**
    * This defines the resource that will be created through this import process.   *\'contact\'* is the only supported *importType* at this stage.
    */
    'importType': string;
    'importOptions': FieldMapping;
    /**
    * The type of contact import that is occurring.
    */
    'importMode': Import.ImportModeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resourceId",
            "baseName": "resourceId",
            "type": "string"
        },
        {
            "name": "importType",
            "baseName": "importType",
            "type": "string"
        },
        {
            "name": "importOptions",
            "baseName": "importOptions",
            "type": "FieldMapping"
        },
        {
            "name": "importMode",
            "baseName": "importMode",
            "type": "Import.ImportModeEnum"
        }    ];

    static getAttributeTypeMap() {
        return Import.attributeTypeMap;
    }
}

export namespace Import {
    export enum ImportModeEnum {
        Replace = <any> 'replace',
        Duplicate = <any> 'duplicate',
        Ignore = <any> 'ignore'
    }
}
