/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MessageResponseDetailedMessageresponsesInnerFrom } from './messageResponseDetailedMessageresponsesInnerFrom';
import { MessageResponseDetailedMessageresponsesInnerResponseMessage } from './messageResponseDetailedMessageresponsesInnerResponseMessage';

export class MessageResponseDetailedMessageresponsesInner {
    'from': MessageResponseDetailedMessageresponsesInnerFrom;
    /**
    * The message response category.  * `noresponse` - the message was sent but was not replied to * `notmatched` - the message was replied to and the answer didn\'t match any search criteria
    */
    'responseCategory': MessageResponseDetailedMessageresponsesInner.ResponseCategoryEnum;
    'responseMessage': MessageResponseDetailedMessageresponsesInnerResponseMessage;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "from",
            "baseName": "from",
            "type": "MessageResponseDetailedMessageresponsesInnerFrom"
        },
        {
            "name": "responseCategory",
            "baseName": "responseCategory",
            "type": "MessageResponseDetailedMessageresponsesInner.ResponseCategoryEnum"
        },
        {
            "name": "responseMessage",
            "baseName": "responseMessage",
            "type": "MessageResponseDetailedMessageresponsesInnerResponseMessage"
        }    ];

    static getAttributeTypeMap() {
        return MessageResponseDetailedMessageresponsesInner.attributeTypeMap;
    }
}

export namespace MessageResponseDetailedMessageresponsesInner {
    export enum ResponseCategoryEnum {
        Noresponse = <any> 'noresponse',
        Notmatched = <any> 'notmatched'
    }
}
