/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The message responder object.
*/
export class MessageResponseDetailedMessageresponsesInnerFrom {
    /**
    * The message responder\'s name.
    */
    'name': string;
    /**
    * The message responder\'s MRI.
    */
    'mri': string;
    /**
    * The message responder\'s mobile number.
    */
    'mobile': string;
    /**
    * The message responder\'s email address.
    */
    'email': string;
    /**
    * The message responder\'s voice number.
    */
    'voice': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "mri",
            "baseName": "mri",
            "type": "string"
        },
        {
            "name": "mobile",
            "baseName": "mobile",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MessageResponseDetailedMessageresponsesInnerFrom.attributeTypeMap;
    }
}

