/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Dlr } from './dlr';
import { Email } from './email';
import { Features } from './features';
import { LinkInner } from './linkInner';
import { Social } from './social';
import { Voice } from './voice';
import { Web } from './web';

/**
* The template object.
*/
export class Template {
    /**
    * Specifies the name of the message template to be used within message requests.
    */
    'messageTemplateName': string;
    /**
    * Specifies the description of the message template for others to understand its purpose.
    */
    'messageTemplateDescription'?: string;
    /**
    * Specifies the ID of the Response Rule that should be associated with this Message Template.
    */
    'responseTemplateId'?: string;
    /**
    * Specifies the first line of the SMS message or Voice call, and the subject of the Email message.
    */
    'subject': string;
    /**
    * Specifies the content of the SMS message.
    */
    'body': string;
    'email'?: Email;
    'voice'?: Voice;
    'web'?: Web;
    'social'?: Social;
    /**
    * Allows the user to modify the message behaviour for replies and DLRs (delivery receipts)
    */
    'type'?: string;
    'features'?: Features;
    'dlr'?: Dlr;
    /**
    * A [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) link object, describing all discoverable resources in relation to the original request.
    */
    'link'?: Array<LinkInner>;
    /**
    * Information which helps to label related message templates together
    */
    'tags'?: string;
    /**
    * specifies the id of the message template
    */
    'id'?: string = '7DB65E1D8853D1C8';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "messageTemplateName",
            "baseName": "messageTemplateName",
            "type": "string"
        },
        {
            "name": "messageTemplateDescription",
            "baseName": "messageTemplateDescription",
            "type": "string"
        },
        {
            "name": "responseTemplateId",
            "baseName": "responseTemplateId",
            "type": "string"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "Email"
        },
        {
            "name": "voice",
            "baseName": "voice",
            "type": "Voice"
        },
        {
            "name": "web",
            "baseName": "web",
            "type": "Web"
        },
        {
            "name": "social",
            "baseName": "social",
            "type": "Social"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "Features"
        },
        {
            "name": "dlr",
            "baseName": "dlr",
            "type": "Dlr"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "Array<LinkInner>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Template.attributeTypeMap;
    }
}

