/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.3
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The web channel payload, used when attaching web content to a Message.  Not required when a template is provided.
*/
export class Web {
    /**
    * The linked web content body.
    */
    'body'?: string;
    /**
    * The web Message content type.
    */
    'type'?: Web.TypeEnum = Web.TypeEnum.Plain;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Web.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return Web.attributeTypeMap;
    }
}

export namespace Web {
    export enum TypeEnum {
        Plain = <any> 'text/plain',
        Html = <any> 'text/html'
    }
}
