name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        id: setup-jre
        uses: actions/setup-java@v2
        with:
          java-version: '18' # always use 18 for building
          distribution: 'temurin'
          architecture: x64

      - name: Set Test Java Runtime Environment variable
        run: echo "JAVA_TEST_HOME=${{ steps.setup-jre.outputs.path }}" >> $GITHUB_ENV

      - name: Build artifacts
        run: ./gradlew assemble
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version: # https://github.com/actions/setup-java#supported-version-syntax
          - '8'
          - '11'
          - '16'
          - '17'
          - '18'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Test Java runtime
        id: setup-test-jre
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          architecture: x64

      - name: Set Test Java Runtime Environment variable
        run: echo "JAVA_TEST_HOME=${{ steps.setup-test-jre.outputs.path }}" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '18' # always use 18 for building
          distribution: 'temurin'
          architecture: x64

      - name: Tweak gradle.properties for Java 1.8
        if: ${{ matrix.java-version == '1.8' }}
        run: sed -e '/--add-exports/ s/^#*/#/' -i gradle.properties

      - name: Display version
        run: |
          ./gradlew --version
          echo "JAVA_TEST_HOME=$JAVA_TEST_HOME"
      - name: Run test suite
        run: ./gradlew test
