name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Node artifacts
        run: yarn
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18]

    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Run test suite
        run: yarn test
      - name: Run Prism test suite
        run: yarn test
